mysite/board/urls.py
from django.urls import path
from . import views

app_name = "board"

urlpatterns = [
    path("", views.board_list, name="list"),
    path("create/", views.board_create, name = "create"),
    path("<int:board_id>/", views.board_read, name="read"),
    path("<int:board_id>/update/", views.board_update, name="update"),
    path("<int:board_id>/delete/", views.board_delete, name="delete"),
    path("download/<int:board_id>/", views.board_download, name="download"),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('tinymce/', include('tinymce.urls')),
    path('board/', include('board.urls')),
    path('common/', include('common.urls')),
]

mysite/board/models.py
from django.db import models

class Board(models.Model):
    title = models.CharField(verbose_name="제목", max_length=100)
    content = models.TextField(verbose_name="내용")
    password = models.CharField(verbose_name="비밀번호", max_length=20)
    created_by = models.CharField(verbose_name="글쓴이", max_length=20)
    created_at = models.DateTimeField(verbose_name="작성일시", auto_now_add=True)
    filename = models.CharField(verbose_name="파일명", max_length=100, null=True, blank=True)
    original_filename = models.CharField(verbose_name="원본파일명", max_length=100, null=True, blank=True)
    
    class Meta:
        db_table = 'board' # 데이터베이스에 저장될 테이블의 이름을 명시적으로 지정
        verbose_name = 'board' # Django Admin에서 이 모델의 이름을 표시할 때 사용할 단수형 이름을 지정
        verbose_name_plural = 'boards' # Django Admin에서 이 모델의 복수형 이름을 지정
        ordering = ['-created_at']

    def __str__(self):
        return self.title

mysite/board/forms.py
from django import forms
from .models import Board
from tinymce.widgets import TinyMCE

# 등록 폼
class BoardForm(forms.ModelForm):
    class Meta:
        model = Board # models.py에서의 class이름
        fields = ["title", "content", "password", "created_by"] # 필드에는 필수적으로 사용자가 넣어야 될 내용만 들어간다.
        widgets = {'test': TinyMCE(attrs={'cols': 80, 'rows': 30})}
        
    def clean_title(self): # clean_칼럼명 : 올바른 제목이 들어왔는지 검증한다.
        title = self.cleaned_data.get("title") # self.cleaned_data.get() : 사용자가 적은 내용 받아오기(trim역할-공백제거)
        if not title:
            raise forms.ValidationError("제목을 입력하세요.") # validationError는 view쪽에서 사용한다.
        if len(title) < 2 or len(title) > 100: # len : 글자수
            raise forms.ValidationError("제목을 2자이상 100자이하로 입력하세요.")
        return title # 깨끗한 정보를 view쪽으로 넘겨준다.
    
    def clean_content(self):
        content = self.cleaned_data.get("content")
        if not content:
            raise forms.ValidationError("내용을 입력하세요.")
        return content
    
    def clean_password(self):
        password = self.cleaned_data.get("password")
        if not password:
            raise forms.ValidationError("비밀번호를 입력하세요.")
        if len(password) < 2 or len(password) > 20:
            raise forms.ValidationError("비밀번호를 2자이상 20자이하로 입력하세요.")
        return password
    
    def clean_created_by(self):
        created_by = self.cleaned_data.get("created_by")
        if not created_by:
            raise forms.ValidationError("글쓴이 이름을 입력하세요.")
        if len(created_by) < 2 or len(created_by) > 20:
            raise forms.ValidationError("글쓴이 이름을 2자이상 20자이하로 입력하세요.")
        return created_by
    

# 삭제 폼
class BoardDeleteForm(forms.ModelForm):
    class Meta:
        model = Board
        fields = ["password"]
        
    def clean_password(self):
        password = self.cleaned_data.get("password")
        if not password:
            raise forms.ValidationError("비밀번호를 입력하세요.")
        return password

mysite/board/views.py
import os
import uuid
from django.http import FileResponse, HttpResponse
from django.shortcuts import render, redirect
from django.contrib import messages
from django.core.paginator import Paginator
from django.db.models import Q

from mysite import settings

from .models import Board
from .forms import BoardForm, BoardDeleteForm

# 등록
def board_create(request):
    # 입력 폼 (비어있는 값)
    form = BoardForm()
    
    # 처리
    if request.method == "POST":
      
        # 입력 폼 (사용자로부터 받은 값)
        form = BoardForm(request.POST) # request : 사용자로 부터 넘어온 정보 # 얘네를 form으로 넘겨준다.
       
        # 입력 폼 유효성 검사
        # 검사 통과
        if form.is_valid(): #is_valid : 검증하는 단계
            board = form.save(commit=False) # 저장
            
            # 파일 업로드
            if request.FILES:
                filename = uuid.uuid4().hex
                file = request.FILES.get("file")
                
                # 파일 저장
                save_path = os.path.join(settings.MEDIA_ROOT, filename)
                with open(save_path, 'wb') as f:
                    for chunk in file.chunks(): # chunk단위로 쪼개서 실행
                        f.write(chunk)
                        
                # 파일이 있을 때만 추가가 되기 때문에 파일이 없으면 밑에 2줄은 blank로 들어간다.
                # models.py에서 blank=True로 해놨기 때문
                board.filename = filename
                board.original_filename = file.name
                
            board.save()
            
            messages.success(request, "게시글이 등록되었습니다.")
            return redirect("board:read", board_id=board.id)
        
        # 검사 실패
        else:
            for field_name, error_messages in form.errors.items():
                messages.error(request, f"{form.fields[field_name].label} : {error_messages[0]}")
    
    # GET 요청일 때 폼 반환
    form = BoardForm()
           
    # 화면
    return render(request, "board/create.html", {"form": form})

    
# 상세보기
def board_read(request, board_id):
    board = Board.objects.get(id=board_id)
    context = {"board": board}
    return render(request, "board/read.html", context)


# 수정
def board_update(request, board_id):
    board = Board.objects.get(id=board_id)
    context = {"board": board}
    old_password = board.password

    # POST 요청일 때
    if request.method == "POST":
        # 입력 폼(사용자로부터 받은 값)
        form = BoardForm(request.POST, instance=board)

        # 입력 폼 유효성 검사
        # 검사 통과
        if form.is_valid():
            new_password = form.cleaned_data.get("password")

            if old_password == new_password:
                # 게시글 수정
                board = form.save(commit=False)  # 들어온 정보를 저장
                
                if request.FILES:
                    # 파일 삭제가 체크되어 있거나 기존 파일이 있으면 기존 파일 삭제
                    if request.POST.get("deleteFile") or board.filename:
                        os.remove(os.path.join(settings.MEDIA_ROOT, board.filename))
                    
                    filename = uuid.uuid4().hex
                    file = request.FILES.get("file")
                    
                    # 파일 저장
                    save_path = os.path.join(settings.MEDIA_ROOT, filename)
                    with open(save_path, 'wb') as f:
                        for chunk in file.chunks():
                            f.write(chunk)
                    
                    board.filename = filename
                    board.original_filename = file.name
                
                board.save()

                messages.success(request, "게시글이 수정되었습니다.")
                return redirect("board:read", board_id=board.id)

            else:
                messages.error(request, "비밀번호가 일치하지 않습니다")

        # 검사 실패
        else:
            for field_name, error_messages in form.errors.items():
                messages.error(
                    request, f"{form.fields[field_name].label}: {error_messages[0]}"
                )
    # GET 요청일 때 빈 폼 반환
    form = BoardForm(instance=board)
    context["form"] = form

    # 화면
    return render(request, "board/update.html", context)


# 삭제
def board_delete(request, board_id):
    board = Board.objects.get(id=board_id)
    old_password = board.password

    if request.method == "POST":
        form = BoardDeleteForm(request.POST)
        if form.is_valid():
            new_password = form.cleaned_data.get("password")
            
            if old_password == new_password:
                # 파일 삭제
                # os.remove(os.path.join(settings.MEDIA_ROOT, board.filename))
                
                # 파일이 존재할 때만 삭제 시도
                file_path = board.filename
                if file_path:  
                    full_path = os.path.join(settings.MEDIA_ROOT, file_path)
                    if os.path.exists(full_path):
                        os.remove(full_path)
                        
                board.delete()
                return HttpResponse("게시글이 삭제되었습니다.")
            else:
                messages.error(request, "비밀번호가 일치하지 않습니다.")
                return redirect("board:read", board_id=board.id)

# 목록
def board_list(request):
    # 테스트 글 추가
    # 예시 글 300개 추가한거라서 300개 필요없으면 주석처리 하면됨(밑에 2줄) 한번만 하면 됨 이미 했다. 지금은 필요없당
    #for i in range(1,300):
       # Board.objects.create(title=f"제목 {i}", content=f"내용  {i}", password="1234", created_by="홍길동")
    page = request.GET.get('page', '1') #page가 없으면 기본 1로 가져온다.
    keyword = request.GET.get('keyword','') #keyword가 없으면 ''을 가져온다.
    search_type = request.GET.get('search_type','')
    boards = Board.objects.all().order_by('-created_at')

    if keyword:
        if search_type == 'title':
            boards = boards.filter(Q(title__icontains=keyword))
        elif search_type == 'content':
            boards = boards.filter(Q(content__icontains=keyword))
        elif search_type == 'created_by':
            boards = boards.filter(Q(created_by__icontains=keyword))
        elif search_type == 'all':
            boards = boards.filter(
                Q(title__icontains=keyword) |
                Q(content__icontains=keyword) |
                Q(created_by__icontains=keyword)
            )
        # Q:장고에서 필터처리를 하기위해 제공해주는 라이브러리
        # 키워드가 있다면 필터를 이용해서 값을 가져온다.
    
    paginator = Paginator(boards, 10)
    page_obj = paginator.get_page(page)

    context = {
        "boards" : page_obj,
        "keyword" : keyword,
        "search_type" : search_type,
    }
    
    return render(request, "board/list.html", context)

# 파일 다운로드
def board_download(request, board_id):
    board = Board.objects.get(id=board_id)
    file_path = os.path.join(settings.MEDIA_ROOT, board.filename)
    return FileResponse(
        open(file_path, 'rb'),
        as_attachment = True,
        filename = board.original_filename
    )

mysite/templates/board/create.html
{% extends "../base.html" %}
{% load my_filter %}
    {% block content %}
    <div class="card-body">
        <form id="createForm" method="POST" enctype="multipart/form-data"> <!--enctype="multipart/form-data"가 있어야 파일 업로드가 가능-->
            {% csrf_token %}
            <div class="mb-3">
                <label for="title" class="form-label">제목</label>
                <input type="text" id="title" name="title" class="form-control" placeholder="제목을 입력하세요." value="{{ form.title.value|default_if_none:'' }}">
            </div>
            {{ form.test }}
            <div class="mb-3">
                <label for="content" class="form-label">내용</label>
                <textarea rows="10" id="content" name="content" class="form-control" placeholder="내용을 입력하세요.">{{ form.content.value|default_if_none:'' }}</textarea>
            </div>
            <div class="mb-3">
                <label for="created_by" class="form-label">글쓴이</label>
                <input type="text" id="created_by" name="created_by" class="form-control" placeholder="글쓴이를 입력하세요." value="{{ form.created_by.value|default_if_none:'' }}">
            </div>
            <div class="mb-3">
                <label for="password" class="form-label">비밀번호</label>
                <input type="password" id="password" name="password" class="form-control" placeholder="비밀번호를 입력하세요.">
            </div>
            <div class="mb-3">
                <label for="file" class="form-label">파일</label>
                <input type="file" id="file" name="file" class="form-control" accept="image/*">
            </div>
            <div>
                <button type="submit" class="btn btn-primary">게시글 등록</button>
                <a href="{% url 'board:list' %}?{% query_string %}" class="btn btn-danger">등록 취소</a>
                <!-- ?{% query_string %} : 이전 창에서 저장되어있던 정보 가지고 온다. -->
            </div>
        </form>
    </div>
    {% endblock %}

    {% block script %}
    <script>
        //tinymce 초기화
        tinymce.init({
            selector: '#content',
            height: 500,
            //menubar: false,
            plugins: [
                'advlist', 'autolink', 'lists', 'link', 'image', 'charmap', 'preview',
                'anchor', 'searchreplace', 'visualblocks', 'code', 'fullscreen',
                'insertdatetime', 'media', 'table', 'help', 'wordcount'
            ],
            toolbar: 'undo redo | blocks | ' +
            'bold italic backcolor | alignleft aligncenter ' +
            'alignright alignjustify | bullist numlist outdent indent | ' +
            'removeformat | help',
            content_style: 'body { font-family:Helvetica,Arial,sans-serif; font-size:16px }'
        });

        //jquery
        $('#title').focus();
        //# : id
        // . :class

        // 입력 폼 유효성 검사
        $('#createForm').on('submit', function(event){
            // 제목 입력 폼 유효성 검사
            if($('#title').val() == '') { //''이면 {}내용을 가져와라, 'a' : a를 넣어라
                alert('제목을 입력하세요.');
                $('#title').focus();
                event.preventDefault();
            }

            // 내용 입력 폼 유효성 검사
            if($('#content').val() == '') {
                alert('내용을 입력하세요.');
                $('#content').focus();
                event.preventDefault();
            }
        
            // 글쓴이 입력 폼 유효성 검사
            if($('#created_by').val() == '') {
                alert('글쓴이를 입력하세요.');
                $('#created_by').focus();
                event.preventDefault();
            }

            // 비밀번호 입력 폼 유효성 검사
            if($('#password').val() == '') {
                alert('비밀번호를 입력하세요.');
                $('#password').focus();
                event.preventDefault();
            }

        });

        /* //바닐라 자바 스크립트
        // 제목 입력 폼에 포커스 설정
        document.getElementById('title').focus();

        document.getElementById('createForm').addEventListener('submit', function(event) {
        //createForm에서 submit이라는 이벤트가 발생한다면 그걸 실행해라
         
        // 제목 입력 폼 유효성 검사
        if (document.getElementById('title').value == '') {
            alert('제목을 입력하세요.');
            //title에 잇는 값을 가져오는데 아무것도 없다면 alert경고창을 띄우고 거기에 포커스를 가져가라
            document.getElementById('title').focus();
            event.preventDefault();//더이상 submit 이벤트를 진행하지 말아라.
        }
        
        // 내용 입력 폼 유효성 검사
        if (document.getElementById('content').value == '') {
            alert('내용을 입력하세요.');
            document.getElementById('content').focus();
            event.preventDefault();
        }
        
        // 글쓴이 입력 폼 유효성 검사
        if (document.getElementById('created_by').value == '') {
            alert('글쓴이를 입력하세요.');
            document.getElementById('created_by').focus();
            event.preventDefault();
        }
    
        // 비밀번호 입력 폼 유효성 검사
        if (document.getElementById('password').value == '') {
            alert('비밀번호를 입력하세요.');
            document.getElementById('password').focus();
            event.preventDefault();
        }
        });
        */
    </script>
    {% endblock %}

mysite/templates/board/list.html
{% extends "../base.html" %}

{% load my_filter %}

{% block content %}
    <!-- 검색, 등록 버튼 -->
    <div class="d-flex justify-content-between">
        <!-- 검색 버튼 -->
        <form action="{% url 'board:list' %}" method="GET">
            <div class="input-group">
                <select name="search_type" class="form-select">
                    <option value="title" {% if search_type == 'title' %}selected{% endif %}>제목</option>
                    <option value="content" {% if search_type == 'content' %}selected{% endif %}>내용</option>
                    <option value="created_by" {% if search_type == 'created_by' %}selected{% endif %}>글쓴이</option>
                    <option value="all" {% if search_type == 'all' %}selected{% endif %}>전체</option>
                </select>
                <input type="text" name="keyword" id="keyword" class="form-control" placeholder="검색어를 입력하세요." value="{{ keyword }}">
                <button type="submit" class="btn btn-primary">검색</button>
                {% if keyword %} <!-- keyword가 있을때만 보이게 -->
                    <a href="{% url 'board:list' %}" class="btn btn-danger">취소</a>
                    <!-- 취소버튼 누르면 board:list로 이동 -->
                {% endif %}
            </div>
        </form>
        <!--// 검색 버튼 -->

        <!-- 등록 버튼 -->
        <a href="{% url 'board:create' %}?{% query_string %}" class="btn btn-primary">게시글 등록</a>
        <!-- ?{% query_string %} : 검색창에 저장되어 있던 정보를 게시글 등록 창에 넘겨준다. -->
        <!--// 등록 버튼 -->
    </div>  
    <!-- 빈 공간을 아래에서 위를 띄우도록 해줘야한다. -->
    <!--// 검색, 등록 버튼 -->

    <!-- 게시글 목록 -->
    <div class="mb-3">
        <table class="table table-striped table-hover table-bordered">
            <thead>
                <tr class="text-center"><!--th에 해당하는 글씨들이 가운데 정렬로 표현된다.-->
                    <th class="col-1">순번</th><!--th: 글씨가 굵고 진하게-->
                    <th class="col-6">제목</th>
                    <th class="col-2">글쓴이</th>
                    <th class="col-3">등록일시</th>
                </tr>
            </thead>
            <tbody>
                {% if boards %}
                    {% for board in boards %}
                    <tr>
                        <td class="text-center">
                            <!-- 번호 = 전체건수 - 시작인덱스 -현재인덱스 + 1 -->
                            {{ boards.paginator.count|minus:boards.start_index|minus:forloop.counter0|add:1 }}
                        </td>
                        <td><a href="{% url 'board:read' board_id=board.id %}">{{ board.title }}</a></td>
                        <td class="text-center">{{ board.created_by }}</td>
                        <td class="text-center">{{ board.created_at | date:"Y-m-d H:i" }}</td>
                    </tr>
                {% endfor %}
                {% else %}
                    <tr>
                        <td class="text-center" colspan="4">게시글이 없습니다.</td>
                    </tr>
                {% endif %}
            </tbody>
        </table>
    </div>
    <!--// 게시글 목록 -->
  
    <!-- 페이징 -->
    <div>
        <nav aria-label="Page navigation">
            <ul class="pagination justify-content-center">
            
                <!-- 이전 페이지 -->
                {% if boards.has_previous %}
                    <li class="page-item">
                        <a class="page-link" href="?{% query_string page=boards.previous_page_number %}">이전</a>
                        <!-- query_string:원래 있는 쿼리에 더 추가해서 확장할꺼야라는 목적을 가진 사용자 정의 필터 -->
                    </li>
                {% endif %}
                <!--// 이전 페이지 -->
                
                <!-- 페이지리스트 -->
                {% for page_number in boards.paginator.page_range %}
                    {% if page_number >= boards.number|add:-5 and page_number <= boards.number|add:5 %}
                    <!-- add:-5 대신 minus:5 사용해도 된다. -->
                        <li class="page-item {% if page_number == boards.number %}active{% endif %}">
                            <a class="page-link" href="{% url 'board:list' %}?{% query_string page=page_number %}">
                                {{ page_number }}
                            </a>
                        </li>
                    {% endif %}
                {% endfor %}  
                <!--// 페이지리스트 -->
  
                <!-- 다음 페이지 --> 
                {% if boards.has_next %}    
                    <li class="page-item">
                        <a class="page-link" href="?{% query_string page=boards.next_page_number %}">다음</a>
                    </li>
                {% endif %}
                <!--// 다음 페이지 -->
            </ul>
        </nav>
    </div>
    <!--// 페이징 -->
    
{% endblock %}
<!--document:웹페이지(문서), getElementById:id로 해당하는 객체를 가져오는 입력폼-->
{% block script %}
    <script>
        // 키워드 입력 폼에 포커스 설정 
        //함수는 동사(명령), 변수는 명사
        document.getElementById('keyword').focus();
    </script>
{% endblock %}

mysite/templates/board/read.html
{% extends "../base.html" %}
{% load my_filter %}

{% block content %}
    <div class="container">
        <div class="card mb-3">
            <div class="card-header">{{ board.title }}</div>
            <div class="card-body">
                <div class="text-end text-muted">
                    <div>글쓴이 : {{ board.created_by }}</div> <!-- text-muted: 글씨를 흐리게 만들어준다. -->
                    <div>등록일시 : {{ board.created_at | date:"Y-m-d H:i" }}</div>
                </div>
                {% if board.filename %}
                <div>
                    첨부파일 : <a href="{% url "board:download" board_id=board.id %}" class="btn btn-primary">{{ board.original_filename }}</a>
                </div>
                {% endif %}
                <div>{{ board.content | markdown_to_html }}</div> <!-- markdown으로 들어온 것을 html로 출력해라. -->
            </div>
        </div>

        <div>
            <a href="{% url 'board:list' %}" class="btn btn-primary">게시글 목록</a>
            <a href="{% url 'board:update' board_id=board.id %}" class="btn btn-warning">게시글 수정</a>
            <button type="button" class="btn btn-danger" data-bs-toggle="modal"
            data-bs-target="#deleteModal">게시글 삭제</button>
        </div>
    </div>

    <!-- 삭제 모달 -->
    <div class="modal fade" id="deleteModal" tabindex="-1" aria-labelledby="deleteModalLabel" aria-hidden="true">
        <!-- Tabindex=-1 : tab을 최우선으로 둔다는 뜻 -->
        <div class="modal-dialog">
            <div class="modal-content">
            <form id="deleteForm" action="{% url 'board:delete' board_id=board.id %}" method="POST">
                {% csrf_token %}
                <div class="modal-header">
                    <h1 class="modal-title fs-5" id="deleteModalLabel">게시글 삭제</h1>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    <!-- data-bs-dismiss : x버튼 -->
                </div>
                <div class="modal-body">
                    <div class="mb-3">
                        <span class="text-danger">삭제된 데이터는 복구할 수 없습니다.</span>비밀번호를 입력해주세요.
                    </div>
                    <div>
                        <input type="password" id="password" name="password" placeholder="비밀번호" class="form-control">
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">삭제 취소</button>
                    <button type="submit" class="btn btn-danger">게시글 삭제</button>
                </div>
            </form>
            </div>
        </div>
    </div>
    <!--// 삭제 모달 -->

{% endblock %}

mysite/templates/board/update.html
{% extends "../base.html" %}

    {% block content %}
    <div class="card-body">
        <form id="updateForm" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="mb-3">
                <label for="title" class="form-label">제목</label>
                <input type="text" id="title" name="title" class="form-control" placeholder="제목을 입력하세요." value="{{ form.title.value|default_if_none:'' }}">
            </div>
            <div class="mb-3">
                <label for="content" class="form-label">내용</label>
                <textarea rows="10" id="content" name="content" class="form-control" placeholder="내용을 입력하세요.">{{ form.content.value|default_if_none:'' }}</textarea>
            </div>
            <div class="mb-3">
                <label for="created_by" class="form-label">글쓴이</label>
                <input type="text" id="created_by" name="created_by" class="form-control" placeholder="글쓴이를 입력하세요." value="{{ form.created_by.value|default_if_none:'' }}">
            </div>
            <div class="mb-3">
                <label for="password" class="form-label">비밀번호</label>
                <input type="password" id="password" name="password" class="form-control" placeholder="비밀번호를 입력하세요.">
            </div>
            <div class="mb-3">
                <label for="file" class="form-label">파일</label>
                <input type="file" id="file" name="file" class="form-control" accept="image/*">
            </div>
            {% if board.filename %}
            <div class="mb-3">
                <label class="form-label">파일 삭제</label>
                <input type="checkbox" id="deleteFile" name="deleteFile" class="form-check-input">
            </div>
            <div class="form-text">
                기존 파일 : <a href="{% url "board:download" board_id=board.id %}" class="btn btn-primary">{{ board.original_filename }}</a>
            </div>
            {% endif %}
            <div>
                <button type="submit" class="btn btn-primary">게시글 수정</button>
                <a href="{% url 'board:read' board_id=board.id %}" class="btn btn-danger">등록 취소</a>
            </div>
        </form>
    </div>
    {% endblock %}