mysite/board/urls.py
from django.urls import path
from . import views

app_name = "board"

urlpatterns = [
    path("", views.board_list, name="list"),
    path("create/", views.board_create, name = "create"),
    path("<int:board_id>/", views.board_read, name="read"),
    path("<int:board_id>/update/", views.board_update, name="update"),
    path("<int:board_id>/delete/", views.board_delete, name="delete"),
    path("download/<int:board_id>/", views.board_download, name="download"),
]

mysite/common/urls.py
from django.urls import path
from . import views

app_name = "common"

urlpatterns = [
    path("register/", views.common_register, name="register"),
    path("find_username/", views.common_find_username, name = "find_username"),
    path("reset_password/", views.common_reset_password, name="reset_password"),
    path("login/", views.common_login, name="login"),
    path("logout/", views.common_logout, name="logout"),
    path("profile/", views.common_profile, name="profile"),
    path("update_profile/", views.common_update_profile, name = "update_profile"),
    path("update_password/", views.common_update_password, name="update_password"),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('tinymce/', include('tinymce.urls')),
    path('board/', include('board.urls')),
    path('common/', include('common.urls')),
]

mysite/common/models.py
from django.db import models

# Create your models here.

mysite/common/forms.py
from django import forms
from django.contrib.auth.models import User

# 등록 폼
class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ["username", "password", "email", "first_name"]
        
    def clean_username(self):
        username = self.cleaned_data.get("username")
        if not username:
            raise forms.ValidationError("사용자 아이디를 입력하세요.")
        if len(username) < 6 or len(username) > 20:
            raise forms.ValidationError("사용자 아이디를 6자이상 20자이하로 입력하세요.")
        return username
    
    def clean_email(self):
       email = self.cleaned_data.get("email")
       if not email:
           raise forms.ValidationError("이메일을 입력하세요.")
       return email
                    
    def clean_password(self):
        password = self.cleaned_data.get("password")
        if not password:
            raise forms.ValidationError("비밀번호를 입력하세요.")
        if len(password) < 8 or len(password) > 20:
            raise forms.ValidationError("사용자 비밀번호를 8자이상 20자이하로 입력하세요.")
        return password
      
    def clean_first_name(self):
        first_name = self.cleaned_data.get("first_name")
        if not first_name:
            raise forms.ValidationError("이름을 입력하세요.")
        return first_name
    

# 로그인 폼
class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField()
            
    def clean_username(self):
        username = self.cleaned_data.get("username")
        if not username:
            raise forms.ValidationError("사용자 아이디를 입력하세요.")
        return username
                        
    def clean_password(self):
        password = self.cleaned_data.get("password")
        if not password:
            raise forms.ValidationError("비밀번호를 입력하세요.")
        return password
      
# 아이디 찾기 폼
class FindUsernameForm(forms.Form):
    email = forms.CharField()
    first_name = forms.CharField()

    def clean_email(self):
       email = self.cleaned_data.get("email")
       if not email:
           raise forms.ValidationError("이메일을 입력하세요.")
       return email
                    
    def clean_first_name(self):
        first_name = self.cleaned_data.get("first_name")
        if not first_name:
            raise forms.ValidationError("이름을 입력하세요.")
        return first_name

# 비밀번호 초기화 폼
class ResetPasswordForm(forms.Form):
    email = forms.CharField()
    first_name = forms.CharField()
    username = forms.CharField()
        
    def clean_username(self):
        username = self.cleaned_data.get("username")
        if not username:
            raise forms.ValidationError("사용자 아이디를 입력하세요.")
        return username
    
    def clean_email(self):
       email = self.cleaned_data.get("email")
       if not email:
           raise forms.ValidationError("이메일을 입력하세요.")
       return email
                          
    def clean_first_name(self):
        first_name = self.cleaned_data.get("first_name")
        if not first_name:
            raise forms.ValidationError("이름을 입력하세요.")
        return first_name

mysite/common/views.py
from django.shortcuts import redirect, render
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout # 있으면 들어있는 정보가 들어오고, 없으면 null값이 들어온다.
from django.contrib.auth.models import User
from .forms import LoginForm, UserForm, FindUsernameForm, ResetPasswordForm

# 사용자 가입 : /common/register/
def common_register(request):
    if request.method == "POST":
        form = UserForm(request.POST)
        if form.is_valid():
            user = User.objects.create_user(
                username = form.cleaned_data["username"],
                password = form.cleaned_data["password"],
                email = form.cleaned_data["email"],
                first_name = form.cleaned_data["first_name"],
            )
            user.save()
            messages.success(request, "회원가입이 완료되었습니다.")
            return redirect("common:login")
        else:
            for field_name, error_messages in form.errors.items():
                messages.error(request, f"{form.fields[field_name].label} : {error_messages[0]}")
            return render(request, "common/register.html", {"form" : form})

    form = UserForm()
    return render(request, "common/register.html", {"form": form})

# 사용자 아이디 찾기 : /common/find_username/
def common_find_username(request):
    if request.method == "POST":
        form = FindUsernameForm(request.POST)
        if form.is_valid():
            user = User.objects.filter( 
                #사용자 정보를 usermodels에서 불러와서 filter를 넣어서 first_name,email이랑 받아온게 같은거 첫번째거 하나만 받아와라
                first_name = form.cleaned_data["first_name"],
                email = form.cleaned_data["email"]
            ).first()
            if user is not None:
                return render(request, "common/find_username.html", {"username" : user.username}) # username이 있다면 넘겨준다.
            else:
                messages.error(request, "존재하지 않는 사용자입니다.")
        else:
           for field_name, error_messages in form.errors.items():
                messages.error(request, f"{form.fields[field_name].label} : {error_messages[0]}")

    form = FindUsernameForm()
    return render(request, "common/find_username.html", {"form": form})

# 랜덤 비밀번호 생성
def generate_password():
    import random
    import string
    length = random.randint(8, 20)
    characters = string.ascii_letters + string.digits + string.punctuation
    password = ''.join(random.choice(characters) for i in range(length))
    
# 사용자 비밀번호 초기화 : /common/reset_password/
def common_reset_password(request):
    if request.method == "POST":
        form = ResetPasswordForm(request.POST)
        if form.is_valid():
            user = User.objects.filter( 
                first_name = form.cleaned_data["first_name"],
                email = form.cleaned_data["email"],
                username = form.cleaned_data["username"]
            ).first()
            if user is not None:
                password = generate_password()
                user.set_password(password)
                user.save()
                return render(request, "common/reset_password.html", {"password" : password})
            else:
                messages.error(request, "존재하지 않는 사용자입니다.")
        else:
           for field_name, error_messages in form.errors.items():
                messages.error(request, f"{form.fields[field_name].label} : {error_messages[0]}")

    form = ResetPasswordForm()
    return render(request, "common/reset_password.html")


# 사용자 로그인 : /common/login/
def common_login(request):
    if request.method == "POST":
        form = LoginForm(request.POST)
        if form.is_valid():
            user = authenticate(
                username = form.cleaned_data["username"],
                password = form.cleaned_data["password"],
            ) # 없으면 None
            if user is not None:
                login(request, user)
                return redirect("common:profile")
            else:
                messages.error(request, "아이디 또는 비밀번호가 일치하지 않습니다.")
        else:
            for field_name, error_messages in form.errors.items():
                messages.error(request, f"{form.fields[field_name].label} : {error_messages[0]}")
            return render(request, "common/login.html", {"form" : form})
        
    form = LoginForm()
    return render(request, "common/login.html", {"form": form})


# 사용자 로그아웃 : /common/logout/
def common_logout(request):
    logout(request)
    return render(request, "common/logout.html")

# 사용자 정보 : /common/profile/
def common_profile(request):
    return render(request, "common/profile.html")

# 사용자 정보 수정 : /common/update_profile/
def common_update_profile(request):
    return render(request, "common/update_profile.html")

# 사용자 비밀번호 수정 : /common/update_password/
def common_update_password(request):
    return render(request, "common/update_password.html")

mysite/templates/common/find_username.html
{% extends "../base.html" %}
{% load my_filter %}
{% block content %}

{% if username %}
<div class="alert alert-success alert-dismissible fade now" role="alert">
    아이디는 <strong>{{ username }}</strong>입니다.
    <button class="btn-close" type="button" data-bs-dismiss="alert" aria-label="Close"></button>
</div>
{% endif %}

<div class="card col-md-4">
    <div class="card-body">
        <form id="find_usernameForm" method="POST">
            {% csrf_token %}
            <div class="mb-3">
                <label for="first_name" class="form-label">이름</label>
                <input type="text" id="first_name" name="first_name" class="form-control" placeholder="이름을 입력하세요." value="{{ form.first_name.value|default_if_none:'' }}">
            </div>
            <div class="mb-3">
                <label for="email" class="form-label">이메일</label>
                <input type="text" id="email" name="email" class="form-control" placeholder="이메일을 입력하세요." value="{{ form.email.value|default_if_none:'' }}">
            </div>
            <div>
                <button type="submit" class="btn btn-primary">아이디 찾기</button>
                <a href="{% url 'common:reset_password' %}" class="btn btn-warning">비밀번호 초기화</a>
                <a href="{% url 'common:login' %}" class="btn btn-primary">로그인</a>
                <a href="{% url 'common:register' %}" class="btn btn-success">회원가입</a>

            </div>
        </form>
    </div>
</div>
{% endblock %}

{% block script %}
    <script>
        //jquery
        $('#first_name').focus();
        //# : id
        // . :class

        // 입력 폼 유효성 검사
        $('#find_usernameForm').validate({
            rules: {
                first_name: {
                    required: true,
                },
                email: {
                    required: true,
                    email: true,
                },
            },
            messages: {
                first_name: {
                    required: '이름을 입력하세요.',
                },
                email: {
                    required: '이메일을 입력하세요.',
                    email: '올바른 이메일 형식을 입력하세요.',
                },
            },
            errorClass: 'is-invalid',
            validClass: 'is-valid',

            errorPlacement: function(error, element) {
                error.addClass('invalid-feedback');
                element.closest('.mb-3').append(error);
            },
            highlight: function(element, errorClass, validClass) {
                $(element).addClass(errorClass).removeClass(validClass);
            },
            unhighlight: function(element, errorClass, validClass) {
                $(element).addClass(validClass).removeClass(errorClass);
            },
            submitHandler: function(form) {
                form.submit();
            },
        });


        /*
        // 입력 폼 유효성 검사
        $('#registerForm').on('submit', function(event){
            // 이름 입력 폼 유효성 검사
            if($('#first_name').val() == '') { 
                alert('이름을 입력하세요.');
                $('#first_name').focus();
                event.preventDefault();
                return false;
            }

            // 이메일 입력 폼 유효성 검사
            if($('#email').val() == '') {
                alert('이메일을 입력하세요.');
                $('#email').focus();
                event.preventDefault();
                return false;
            }
        
            // 아이디 입력 폼 유효성 검사
            if($('#username').val() == '') {
                alert('아이디를 입력하세요.');
                $('#username').focus();
                event.preventDefault();
                return false;
            }

            // 비밀번호 입력 폼 유효성 검사
            if($('#password').val() == '') {
                alert('비밀번호를 입력하세요.');
                $('#password').focus();
                event.preventDefault();
                return false;
            }
            
            // 비밀번호 확인 입력 폼 유효성 검사
            if($('#password_check').val() == '') {
                alert('비밀번호 확인을 입력하세요.');
                $('#password_check').focus();
                event.preventDefault();
                return false;
            }

            // 비밀번호와 비밀번호 확인이 일치하는지 검사
            if($('#password').val() != $('#password_check').val()) {
                alert('비밀번호와 비밀번호 확인이 일치하지 않습니다.');
                $('#password').focus();
                event.preventDefault();
                return false;
            }

        });
        */
    </script>
{% endblock %}

mysite/templates/common/login.html
{% extends "../base.html" %}
{% load my_filter %}
{% block content %}
<div class="card col-md-4">
    <div class="card-body">
        <form id="loginForm" method="POST">
            {% csrf_token %}
            <div class="mb-3">
                <label for="username" class="form-label">아이디</label>
                <input type="text" id="username" name="username" class="form-control" placeholder="아이디를 입력하세요." value="{{ form.username.value|default_if_none:'' }}">
            </div>
            <div class="mb-3">
                <label for="password" class="form-label">비밀번호</label>
                <input type="password" id="password" name="password" class="form-control" placeholder="비밀번호를 입력하세요.">
            </div>
            <div>
                <button type="submit" class="btn btn-primary">로그인</button>
                <a href="{% url 'common:register' %}" class="btn btn-danger">회원가입</a>
                <a href="{% url 'common:find_username' %}" class="btn btn-success">아이디 찾기</a>
                <a href="{% url 'common:reset_password' %}" class="btn btn-warning">비밀번호 초기화</a>
            </div>
        </form>
    </div>
</div>
{% endblock %}

{% block script %}
    <script>
        //jquery
        $('#username').focus();
        //# : id
        // . :class

        // 입력 폼 유효성 검사
        $('#loginForm').validate({
            rules: {
                username: {
                    required: true,
                },
                password: {
                    required: true,
                },
            },
            messages: {
                username: {
                    required: '아이디를 입력하세요.',
                },
                password: {
                    required: '비밀번호를 입력하세요.',
                },
            },

            errorClass: 'is-invalid',
            validClass: 'is-valid',

            errorPlacement: function(error, element) {
                error.addClass('invalid-feedback');
                element.closest('.mb-3').append(error);
            },
            highlight: function(element, errorClass, validClass) {
                $(element).addClass(errorClass).removeClass(validClass);
            },
            unhighlight: function(element, errorClass, validClass) {
                $(element).addClass(validClass).removeClass(errorClass);
            },
            submitHandler: function(form) {
                form.submit();
            },
        });


        /*
        // 입력 폼 유효성 검사
        $('#registerForm').on('submit', function(event){
            // 이름 입력 폼 유효성 검사
            if($('#first_name').val() == '') { 
                alert('이름을 입력하세요.');
                $('#first_name').focus();
                event.preventDefault();
                return false;
            }

            // 이메일 입력 폼 유효성 검사
            if($('#email').val() == '') {
                alert('이메일을 입력하세요.');
                $('#email').focus();
                event.preventDefault();
                return false;
            }
        
            // 아이디 입력 폼 유효성 검사
            if($('#username').val() == '') {
                alert('아이디를 입력하세요.');
                $('#username').focus();
                event.preventDefault();
                return false;
            }

            // 비밀번호 입력 폼 유효성 검사
            if($('#password').val() == '') {
                alert('비밀번호를 입력하세요.');
                $('#password').focus();
                event.preventDefault();
                return false;
            }
            
            // 비밀번호 확인 입력 폼 유효성 검사
            if($('#password_check').val() == '') {
                alert('비밀번호 확인을 입력하세요.');
                $('#password_check').focus();
                event.preventDefault();
                return false;
            }

            // 비밀번호와 비밀번호 확인이 일치하는지 검사
            if($('#password').val() != $('#password_check').val()) {
                alert('비밀번호와 비밀번호 확인이 일치하지 않습니다.');
                $('#password').focus();
                event.preventDefault();
                return false;
            }

        });
        */
    </script>
{% endblock %}

mysite/templates/common/profile.html
{% extends "../base.html" %}
{% load my_filter %}
{% block content %}
<div class="card col-md-4">
    <div class="card-body">
        <table class="table table-bordered">
            <tr>
                <th>아이디</th>
                <td>{{ user.username }}</td>
            </tr>
            <tr>
                <th>가입일</th>
                <td>{{ user.date_joined|date:"Y-m-d H:i" }}</td>
            </tr>
            <tr>
                <th>최근 접속일</th>
                <td>{{ user.last_login|date:"Y-m-d H:i" }}</td>
            </tr>

        </table>
        <div class="mt-3">
            <a href="{% url 'common:update_profile' %}" class="btn btn-warning">회원정보 수정</a>
            <a href="{% url 'common:update_password' %}" class="btn btn-warning">비밀번호 변경</a>
            <a href="{% url 'common:logout' %}" class="btn btn-danger">로그아웃</a>
        </div>
    </div>
</div>
{% endblock %}

mysite/templates/common/register.html
{% extends "../base.html" %}
{% load my_filter %}
{% block content %}
<div class="card col-md-4">
    <div class="card-body">
        <form id="registerForm" method="POST">
            {% csrf_token %}
            <div class="mb-3">
                <label for="first_name" class="form-label">이름</label>
                <input type="text" id="first_name" name="first_name" class="form-control" placeholder="이름을 입력하세요." value="{{ form.first_name.value|default_if_none:'' }}">
            </div>
            <div class="mb-3">
                <label for="email" class="form-label">이메일</label>
                <input type="text" id="email" name="email" class="form-control" placeholder="이메일을 입력하세요." value="{{ form.email.value|default_if_none:'' }}">
            </div>
            <div class="mb-3">
                <label for="username" class="form-label">아이디</label>
                <input type="text" id="username" name="username" class="form-control" placeholder="아이디를 입력하세요." value="{{ form.username.value|default_if_none:'' }}">
            </div>
            <div class="mb-3">
                <label for="password" class="form-label">비밀번호</label>
                <input type="password" id="password" name="password" class="form-control" placeholder="비밀번호를 입력하세요.">
            </div>
            <div class="mb-3">
                <label for="password_check" class="form-label">비밀번호 확인</label>
                <input type="password" id="password_check" name="password_check" class="form-control" placeholder="비밀번호를 입력하세요.">
            </div>

            <div>
                <button type="submit" class="btn btn-primary">사용자 등록</button>
                <a href="{% url 'common:login' %}" class="btn btn-danger">등록 취소</a>
            </div>
        </form>
    </div>
</div>
{% endblock %}

{% block script %}
    <script>
        //jquery
        $('#first_name').focus();
        //# : id
        // . :class

        // 입력 폼 유효성 검사
        $('#registerForm').validate({
            rules: {
                first_name: {
                    required: true,
                    minlength: 2,
                    maxlength: 10,
                },
                email: {
                    required: true,
                    email: true, //email 필드 규칙 수정
                },
                username: {
                    required: true,
                    minlength:6,
                    maxlength: 20,
                },
                password: {
                    required: true,
                    minlength: 8,
                    maxlength: 20,
                },
                password_check: {
                    required: true,
                    equalTo: '#password', //password와 password_check가 같아야 한다.
                },
            },
            messages: {
                first_name: {
                    required: '이름을 입력하세요.',
                    minlength: '이름은 최소 2자 이상이어야 합니다.',
                    maxlength: '이름은 최대 10자 이하이어야 합니다.',
                },
                email: {
                    required: '이메일을 입력하세요.',
                    email: '올바른 이메일 형식을 입력하세요.',
                },

                username: {
                    required: '아이디를 입력하세요.',
                    minlength: '아이디는 최소 6자 이상이어야 합니다.',
                    maxlength: '아이디는 최대 20자 이하이어야 합니다.',
                },
                password: {
                    required: '비밀번호를 입력하세요.',
                    minlength: '비밀번호는 최소 8자 이상이어야 합니다.',
                    maxlength: '비밀번호는 최대 20자 이하이어야 합니다.',
                },
                password_check: {
                    required: '비밀번호 확인을 입력하세요.',
                    equalTo: '비밀번호와 비밀번호 확인이 일치하지 않습니다.'
                },
            },
            errorClass: 'is-invalid',
            validClass: 'is-valid',
            //에러메세지가 어디에 위치할꺼냐, invalid_feedback에 위치할꺼고, 끝에 mb-3만큼 넣어줄꺼야.
            errorPlacement: function(error, element) {
                error.addClass('invalid-feedback');
                element.closest('.mb-3').append(error);
            },
            highlight: function(element, errorClass, validClass) {
                $(element).addClass(errorClass).removeClass(validClass);
            },
            unhighlight: function(element, errorClass, validClass) {
                $(element).addClass(validClass).removeClass(errorClass);
            },
            submitHandler: function(form) {
                form.submit();
            },
        });


        /*
        // 입력 폼 유효성 검사
        $('#registerForm').on('submit', function(event){
            // 이름 입력 폼 유효성 검사
            if($('#first_name').val() == '') { 
                alert('이름을 입력하세요.');
                $('#first_name').focus();
                event.preventDefault();
                return false;
            }

            // 이메일 입력 폼 유효성 검사
            if($('#email').val() == '') {
                alert('이메일을 입력하세요.');
                $('#email').focus();
                event.preventDefault();
                return false;
            }
        
            // 아이디 입력 폼 유효성 검사
            if($('#username').val() == '') {
                alert('아이디를 입력하세요.');
                $('#username').focus();
                event.preventDefault();
                return false;
            }

            // 비밀번호 입력 폼 유효성 검사
            if($('#password').val() == '') {
                alert('비밀번호를 입력하세요.');
                $('#password').focus();
                event.preventDefault();
                return false;
            }
            
            // 비밀번호 확인 입력 폼 유효성 검사
            if($('#password_check').val() == '') {
                alert('비밀번호 확인을 입력하세요.');
                $('#password_check').focus();
                event.preventDefault();
                return false;
            }

            // 비밀번호와 비밀번호 확인이 일치하는지 검사
            if($('#password').val() != $('#password_check').val()) {
                alert('비밀번호와 비밀번호 확인이 일치하지 않습니다.');
                $('#password').focus();
                event.preventDefault();
                return false;
            }

        });
        */
    </script>
{% endblock %}

mysite/templates/common/reset_password.html
{% extends "../base.html" %}
{% load my_filter %}

{% block content %}
{% if password %}
<div class="alert alert-success alert-dismissible fade now" role="alert">
    아이디는 <strong>{{ password }}</strong>입니다.
    <button class="btn-close" type="button" data-bs-dismiss="alert" aria-label="Close"></button>
</div>
{% endif %}

<div class="card col-md-4">
    <div class="card-body">
        <form id="reset_passwordForm" method="POST">
            {% csrf_token %}
            <div class="mb-3">
                <label for="first_name" class="form-label">이름</label>
                <input type="text" id="first_name" name="first_name" class="form-control" placeholder="이름을 입력하세요." value="{{ form.first_name.value|default_if_none:'' }}">
            </div>
            <div class="mb-3">
                <label for="email" class="form-label">이메일</label>
                <input type="text" id="email" name="email" class="form-control" placeholder="이메일을 입력하세요." value="{{ form.email.value|default_if_none:'' }}">
            </div>
            <div class="mb-3">
                <label for="username" class="form-label">아이디</label>
                <input type="text" id="username" name="username" class="form-control" placeholder="아이디를 입력하세요." value="{{ form.username.value|default_if_none:'' }}">
            </div>
            <div>
                <button type="submit" class="btn btn-primary">비밀번호 초기화</button>
                <a href="{% url 'common:find_username' %}" class="btn btn-warning">아이디 찾기</a>
                <a href="{% url 'common:login' %}" class="btn btn-primary">로그인</a>
                <a href="{% url 'common:register' %}" class="btn btn-success">회원가입</a>
            </div>
        </form>
    </div>
</div>
{% endblock %}

{% block script %}
    <script>
        //jquery
        $('#first_name').focus();
        //# : id
        // . :class

        // 입력 폼 유효성 검사
        $('#reset_passwordForm').validate({
            rules: {
                first_name: {
                    required: true,
                },
                email: {
                    required: true,
                    email: true,
                },
                username: {
                    required: true,
                },
            },
            messages: {
                first_name: {
                    required: '이름을 입력하세요.',
                },
                email: {
                    required: '이메일을 입력하세요.',
                    email: '올바른 이메일 형식을 입력하세요.',
                },
                username: {
                    required: '아이디를 입력하세요.',
                },

            },
            errorClass: 'is-invalid',
            validClass: 'is-valid',

            errorPlacement: function(error, element) {
                error.addClass('invalid-feedback');
                element.closest('.mb-3').append(error);
            },
            highlight: function(element, errorClass, validClass) {
                $(element).addClass(errorClass).removeClass(validClass);
            },
            unhighlight: function(element, errorClass, validClass) {
                $(element).addClass(validClass).removeClass(errorClass);
            },
            submitHandler: function(form) {
                form.submit();
            },
        });


        /*
        // 입력 폼 유효성 검사
        $('#registerForm').on('submit', function(event){
            // 이름 입력 폼 유효성 검사
            if($('#first_name').val() == '') { 
                alert('이름을 입력하세요.');
                $('#first_name').focus();
                event.preventDefault();
                return false;
            }

            // 이메일 입력 폼 유효성 검사
            if($('#email').val() == '') {
                alert('이메일을 입력하세요.');
                $('#email').focus();
                event.preventDefault();
                return false;
            }
        
            // 아이디 입력 폼 유효성 검사
            if($('#username').val() == '') {
                alert('아이디를 입력하세요.');
                $('#username').focus();
                event.preventDefault();
                return false;
            }

            // 비밀번호 입력 폼 유효성 검사
            if($('#password').val() == '') {
                alert('비밀번호를 입력하세요.');
                $('#password').focus();
                event.preventDefault();
                return false;
            }
            
            // 비밀번호 확인 입력 폼 유효성 검사
            if($('#password_check').val() == '') {
                alert('비밀번호 확인을 입력하세요.');
                $('#password_check').focus();
                event.preventDefault();
                return false;
            }

            // 비밀번호와 비밀번호 확인이 일치하는지 검사
            if($('#password').val() != $('#password_check').val()) {
                alert('비밀번호와 비밀번호 확인이 일치하지 않습니다.');
                $('#password').focus();
                event.preventDefault();
                return false;
            }

        });
        */
    </script>
{% endblock %}